name: Deploy branch

on:
  workflow_dispatch:
    inputs:
      cluster:
        description: 'Det clusteret branchen skal deployes til'
        required: true
        type: string

permissions:
  packages: write
  id-token: write

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
      - name: Gradle build
        run: ./gradlew build
      - name: Build and push image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: min-side
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}

  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Deployer ${{ github.ref_name }} til ${{ inputs.cluster }}'
        uses: 'nais/deploy/actions/deploy@v2'
        env:
          CLUSTER: ${{ inputs.cluster }}
          RESOURCE: ./nais/${{ inputs.cluster }}/nais.yaml
          VAR: image=${{ needs.build.outputs.image }}
          PRINT_PAYLOAD: true
          REF: ${{ github.sha }}
